version: '3.8'
services:
  web:
    build: .
    env_file: 
      - .env
    environment:
      MONGO_DB_URL: ${MONGO_DB_URL:-mongodb://mongo/website}
    ports:
      - '${LISTEN:-3000}:3000'
    restart: unless-stopped

  mongo:
    image: mongo:4.4.8
    restart: unless-stopped
