version: "3.8"
services:
  web:
    build: .
    environment:
      CLIENT_ID:
      SECRET:
      BASE_URL:
      MONGO_DB_URL: ${MONGO_DB_URL:-mongodb://mongo/website}
    ports:
      - "3000:3000"
    restart: unless-stopped
  
  mongo:
    image: mongo
    restart: unless-stopped