name: 'CI'
on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: [prettier, eslint, depcheck]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: NPM install
        run: npm install

      - name: Check ${{ matrix.linter }} linter
        run: npm run lint:${{ matrix.linter }}

  build:
    runs-on: ubuntu-latest
    needs: lint
	if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Docker build and publish to ghcr.io
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
